### ISSUE TITLE
刚刚更新TP6到6.0.6导致think-template报错！

### ISSUE THREAD

**Issue by etjson** [top-think/think-template#11]
[ob_implicit_flush(): Argument #1 ($enable) must be of type bool, int given][/www/wwwroot/xxxxx.com/vendor/topthink/think-template/src/Template.php][248]

**Comment by etjson** [comment]
切换到了PHP8，thnik-template尽快更新啊！不然还是要用回PHP7

**Comment by aweihaitun** [comment]
我这边也遇到同样的问题，希望尽快修复一下，谢谢啦

**Comment by liu21st** [comment]
这个早就改过的 今天上午刚发了版本

**Comment by liapples** [comment]
升级一下就可以了
php composer update topthink/think-template
