### ISSUE TITLE
不支持跨模块模块@控制器/操作

### ISSUE THREAD

**Issue by ken678** [top-think/think-template#4]
https://www.kancloud.cn/manual/think-template/1286413手册写了模块@控制器/操作

**Comment by SmallOyster** [comment]
+1……期待官方修复bug

**Comment by SmallOyster** [comment]
@liu21st https://github.com/top-think/think-template/pull/7 ，我在tp6环境是可用的，请检查

**Comment by ken678** [comment]
> @liu21st [https://github.com/top-think/think-template/pull/7，我在tp6环境是可用的，请检查](https://github.com/top-think/think-template/pull/7%EF%BC%8C%E6%88%91%E5%9C%A8tp6%E7%8E%AF%E5%A2%83%E6%98%AF%E5%8F%AF%E7%94%A8%E7%9A%84%EF%BC%8C%E8%AF%B7%E6%A3%80%E6%9F%A5)

我大概看了下 你这个代码以前官方是有的  后来更新给删除@功能了

**Comment by SmallOyster** [comment]
> > @liu21st [https://github.com/top-think/think-template/pull/7](https://github.com/top-think/think-template/pull/7)，我在tp6环境是可用的，请检查
> 
> 我大概看了下 你这个代码以前官方是有的 后来更新给删除@功能了

关于@那个if就是直接从旧版搬过来的，只不过我再根据tp6的情况再做了一些修改

**Comment by zhlhuang** [comment]
支持，我说下我的需求场景，一个模块中 A include B了，然后在另一个模块中想要 include A就会出现B路劲问题。

**Comment by liu21st** [comment]
对于独立的模板引擎来说 没有所谓的模块的概念
